let messages = [
  ["Start off by picking a color from the options in the bottom left. When you're ready, hit the right arrow key on your keyboard to view the next step!",
    "You can hit the left arrow key to go back a step. Let's draw a square in the middle of your canvas. Watch out for that timer; if it runs out, nothing happens.",
    "No punishment :>. Draw a vertical line that cuts the square in half. If you mess up, you can use the white color or the clear all trashcan on the top right.",
    "Then draw another horizontal line that cuts the square into four pieces.",
    "Now write down what you have drawn in the textbox below."],
  ["We're going to start with a yummy dish. Draw a pizza with one slice removed.",
    "Oopsie-dopsie, the pepperoni fell off. Draw a line of small circles moving away from where you removed the slice.",
    "This one is very easy; also, no need to add spaces in your answer."],
  ["Oh yeah, you see that right arrow on the bottom right? You can use it to skip a question. Also, you only have 3 chances to skip, shown by the hearts.",
    "Do not skip if you can figure it out. Start by drawing a circle in the middle of your canvas.",
    "Then draw a right-ward facing arrow in the middle of the circle like a greater-than sign.",
    "Above the arrow, to both left and right, draw two small vertical lines within the circle.",
    "Below the arrow, draw a wide U shape.",
    "To the left and right of the circle, make two curved lines that meet each other at one point to the far right.",
    "Good luck; it is going to get harder."],
  ["Big champ, let us start by drawing a horizontal rectangle in the middle of the screen.",
    "Add a horizontal line on the left side of the rectangle. And add a slim circle on top of that horizontal line.",
    "Now go to the right side of the rectangle and draw a triangle connecting with the rectangle.",
    "Inside the rectangle, add some lines starting from the left to the right of the rectangle.",
    "Good luck writing the answer."],
  ["Let's start by drawing a circle in the middle of your canvas.",
    "In the middle of the circle, draw a triangle pointing to the top.",
    "Above that triangle, draw two horizontal lines, one on the left and the other on the right.",
    "Now go above the circle and  draw two triangles, one to the left and the other to the right pointing upwards.",
    "Also, go back to the triangle you drew in the middle of the circle and to the left of it, draw 3 horizontal lines on top of each other.",
    "Do the same thing for the right side.",
    "Also, draw two curved lines coming out from the lowest tip of that triangle facing opposite directions. Oh, there is something important in the next slide.",
    "See that switch on the bottom? Click it and draw; see the magic :)"],
  ["It is hot outside; why don't you draw an upside-down triangle in the middle of the canvas?",
    "Then, on top of that triangle you drew, put one circle to the left and the other to the right, make sure they are touching.",
    "On top of the two circles you drew, add another circle on top of them in the middle.",
    "Now, inside the triangle, add a bunch of diagonal lines going from left to right and right to left.",
    "No need to add spaces <:."],
  ["Hey, draw a long rectangle like a bill on your page.",
    "Add two circular pennies to the bill on the bottom of each corner; no, the bill cannot fly.",
    "Now put some sticky notes along the bill here.",
    "The bill looks to be stained on the top right corner.",
    "Hopefully, the money is okay."],
  ["Start off by drawing a circle to the left of the canvas and another to the right; make sure to leave a good amount of distance between them.",
    "Now draw a straight vertical line starting from the right of each circle.",
    "Between the two circles, draw two diagonal lines, start from left to right for the first line and for the second line, go from right to left.",
    "Think about it and try thinking outside the box this time. One Question do you like math?"],
  ["Here is a secret: you can use your mouse scroll to increase the size of the stroke, so why don't you do so?",
    "Split the canvas into three sections using vertical lines.",
    "Fill the first section with red, the second with white, and the third with red.",
    "In the middle section, oh come on, you should know this."],
  ["Draw a table in the middle of the canvas.",
    "Add a triangular chair on the top of the table with the tip facing away from the table.",
    "Add another 2 triangular chairs to the bottom left and right corners of the table.",
    "Draw a circular plate near the top of the table.",
    "Add squiggly lines to the bottom of the table like a carpet.",
    "Hopefully, you have a rocking day."]
];